In [ ]:
Nume studenti: Manole Alexandra, Mihaescu Teodor Adrian

# Laborator 2

Saptamana 2-6 martie 2020

Continut:
1. Setup
1. Exercitii cu functii
1. Exercitii cu NumPy

## Setup

Formati ecipe de cate doi. Creati un repository *privat* pe github, cu numele: IDS_NumeFamilieStudent1_NumeFamilieStudent2. Indiferent de grupa din care faceti parte, adaugati ca si colaboratori pe acest repo utilizatorii: akerestely si lmsasu.

Resurse:
1. [Setare de repository privat](https://help.github.com/en/github/administering-a-repository/setting-repository-visibility)
1. [Clienti de git](https://www.hostinger.com/tutorials/best-git-gui-clients/)

Creati un fisier README.md in care sa sa figureze: Numele materiei si numele complet al studentilor din grup. 

## Exercitii cu functii

Nota: aceste exercitii nu se puncteaza. 

1. Sa se scrie o functie care primeste ca parametru o lista de numere si returneaza un tuplu continand: suma elementelor si diferenta maxima dintre elementele listei.
1. Scrieti o functie care preia doua liste si returneaza `True` daca cele doua liste de numere contin cel putin $k$ elemente comune ($k \ge 1$ dat ca parametru intreg, valoare implicita 1), `False` altfel.
1. Sa se scrie o functie care determina daca o lista contine cuvinte reprezentand doar numere intregi (optional: numere fractionare, scrise sub forma parte intreaga, optional urmata de punct zecimal, optional urmata de parte fractionara: 1, 2., 13.14) (Puteti folosi modulul `re` pentru lucrul cu expresii regulate.) Functia trebuie sa testeze daca:
    1. elementele din lista sunt stringuri
    2. fiecare din stringuri este un numar
1. Sa se scrie o functie care returneaza numarul de vocale si de consoane dintr-un parametru dat - rezultatul returnat de functie este tuplu cu doua valori. Cuvantul se va converti la litere mici in interiorul functiei.
1. Sa se scrie o functie care primind o lista de dictionare, returneaza `True` daca toate dictionarele contin cel putin $n$ elemente, $n$ transmis ca parametru, `False` altfel.
1. Sa se scrie o functie recursiva care sa faca ridicarea la putere a unui numar, astfel:
$$
a^n = \begin{cases}
a & \text{daca }n=1
\\
\left(a^{n//2}\right)^2 & \text{daca } n \text{ e par}
\\
\left(a^{n//2}\right)^2 \cdot a & \text{daca } n \text{ e impar}, n>1
\\
\end{cases}
$$
unde prin $n//2$ se reprezinta catul impartirii intregi intre $n$ si 2.

In [2]:
import numpy as np
from typing import List, Tuple, Dict

In [101]:
def ex1(l: List[int]) -> Tuple[int,int]: 
    return np.sum(l), np.max(np.diff(l))
ex1([1, 2, 5, -7, 26])

(27, 33)

In [102]:
def ex2(l1: List[int], l2: List[int], k: int = 1) -> bool:
    return np.intersect1d(l1,l2).size >= k
ex2([1, 2, 3], [3, 4, 5])

True

In [103]:
import re

def ex3(l: List[str]) -> bool:
    r = re.compile(r"[-+]?\d+(\.\d*)?$")
    return np.vectorize(lambda x: bool(r.match(x)))(l)
ex3(['2.4', '15', '-4', '5.', '-4.2', 'test'])

array([ True,  True,  True,  True,  True, False])

In [104]:
def ex4(s: str) -> Tuple[int, int]:
    counter = np.count_nonzero(np.array([True for each in s.lower() if each in "aeiou"]))
    return (counter, len(s) - counter)
ex4("cuvant")

(2, 4)

In [105]:
def ex5(ldict: List[Dict], n: int) -> bool: return all([len(x) >= n for x in ldict])
    
print(ex5([{3: 'test', 4: 'test'},{5: 'doi'}], 1))

True


In [106]:
# ex6 ...

## Exercitii simple folosind NumPy  

Nota: in rezolvarea exercitiilor se vor folosi cat mai mult functii NumPy *vectorizate*. Functiile scrise de voi vor fi documentate cu docstrings (tutoriale: Docstrings in Python, urmati NumPy Style Python Docstrings). Folositi type annotations. Utilizati doar pachetele NumPy.

1. (0.5 puncte) Pentru un vector NumPy dat, sa se determine care sunt elementele unice, in ordine descrescatoare. Exemplu: pentru `x = np.array([-4, 3,  5, 3, 2, 1, -3, -4, 2, -4])` functia scrisa de dvs va intoarce rezultatul `[ 5,  3,  2,  1, -3, -4]`.
1. (0.5 puncte) Pentru un vector NumPy dat, sa se determine care e elementul cel mai frecvent si cel mai putin frecvent (tuplu de 2 valori). Daca exista mai multe numere cele mai frecvente (cele mai putin frecvente), se va raporta oricare din ele. Exemplu: pentru `x = np.array([-4, 3,  5, 3, 2, 1, -3, -4, 2, -4])` functia scrisa de dvs va intoarce rezultatul `(-4, -3)`. 
1. (0.5 puncte) Plecand de la o matrice, sa se scrie o functie care returneaza vectorul minimelor de pe linii si vectorul maximelor de pe coloane. Exemplu: pentru matricea `mat = np.array([[1, 2, 3, 4], [1, -2, 3, -4], [3, 10, 3, 4]])` functia va returna tuplul de vectori: `(array([ 1, -4,  3]), array([ 3, 10,  3,  4]))`. Indicatie:  folositi-va de parametrul `axis`.
1. (0.5 puncte) Pentru o matrice de numere, sa se determine produsul elementelor pe linii sau de pe coloane, in functie de valoarea unui parametru boolean `compute_on_lines`. Exemplu: pentru matricea `mat = np.array([[1, 2, 3, 4], [1, -2, 3, -4], [3, 10, 3, 4]])` si parametrul `compute_on_lines=True`, functia va returna vectorul `[ 24  24 360]`, iar pentru `compute_on_lines=False` se va returna `[  3 -40  27 -64]`.
1. (0.5 puncte) Determinati daca macar unul din elementele unei matrice `a` este mai mare decat cel de pe pozitie corespondenta din `b` (adica daca avem macar o pereche de indecsi (i, j) pentru care a[i, j] > b[i, j]). Daca da, se va returna o astfel de pereche de indecsi; daca nu, se va returna None.
1. (0.5 puncte) Construiti o functie care, primind o matrice, determina pe ce pozitii se afla valorile in afara unui interval [min, max] dat prin parametri.
1. (1 punct) Se considera vectorul: `a = np.array([230, 10, 284, 39, 76])`. Folosind indexarea logica, sa se inmulteasca elementele din vector care sunt mai mici ca 100 cu 2 (restul raman neschimbate). Folosind ciclare, sa se aplice aceeasi operatie pana cand toate elementele devin mai mari ca 100. Sa se afiseze din vectorul final elementele care sunt mai mari de 150 si mai mici de 200.
1. (1 punct) Sa se scrie o functie `pair_max` care preia doi vectori de aceeasi lungime si returneaza maximele pe pozitiile corespunzatoare:
```python
a = np.array([3, 7, 9, 13, -10, 200, 3])
b = np.array([4, 5, -9, 100, 300, 230, 1])
pair_max(a, b)
#iesire dorita: 
array([  4,   7,   9, 100, 300, 230,   3])
```. Functia va verifica cu `assert` ca vectorii au lungimi egale. 
1. (1 punct) Descarcati setul de date Iris de la adresa 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data', si incarcati-l intr--o matrice NumPy, folosind `np.genfromtxt`.  Alegeti aleator 10 pozitii in matricea de 150 linii si 4 coloane (omiteti ultima coloana, de tip text), setati aceste valori pe NaN. Construiti o functie care, primind la intrare o matrice, returneaza un tuplu cu indicii de linii respectiv de coloane in care se gasesc valori NaN.
1. (1 punct) Sa se construiasca o functie care returneaza cele mai mici `k` valori dintr-un vector de cel putin `k` elemente, impreuna cu pozitiile lor. 

In [2]:
# ex1
def unique_desc(array: np.array):
    """ Preia un vector Numpy si afiseasa toate elemetele unice in ordine
    descrescatoare.
    :param array: vector Numpy
    :return: vector cu valorile unice in ordonate descrescator
    """
   print(np.sort(np.unique(array))[::-1])
    
unique_desc([-4, 3,  5, 3, 2, 1, -3, -4, 2, -4])

[ 5  3  2  1 -3 -4]


In [30]:
# ex2
def frequency(array: np.array) -> Tuple[int, int]:
    """Preia un vector Numpy cu valori pozitive si negative si returneaza
    un tuplu cu elementul cel mai des intalnit si cel mai putin intalnit.
    :param array: vector Numpy cu valori + si -
    :return: tuplu format din cel mai frecvent si mai putin frecvent element
    """
    elem, freq = np.unique(array, return_counts = True)
    return (elem[np.where(freq == np.max(freq))][0], elem[np.where(freq == np.min(freq))][0])

frequency(np.array([-4, 3,  5, 3, 2, 1, -3, -4, 2, -4]))

(-4, -3)

In [108]:
# ex3
def maxim(array: np.array)->Tuple[np.array,np.array]:
    """Preia o matrice si returneaza un tuplu format din vectorul minimelor 
    de pe linii si vectorul maximelor de pe coloane.
    :param array: matrice de forma (m,n)
    :return: tuplu cu vectorii minimelor si maximelor de pe linii si
    respectiv coloane
    """
    return [np.amin(array,axis=1), np.amax(array,axis=0)]

print(maxim([[1, 2, 3, 4], [1, -2, 3, -4], [3, 10, 3, 4]]))

[array([ 1, -4,  3]), array([ 3, 10,  3,  4])]


In [109]:
# ex4
def product(array: np.array,compute_on_lines:bool)->np.array:
    """Preia o matrice de numere si returneaza un vector cu produsul
    elementelor pe linii sau de pe coloane, in functie de valoarea lui 
    compute_on_lines.
    :param array: matrice de numere
    :param compute_on_lines: param de tip boolean
    :return: vector cu produsul elementelor 
    """
    return np.prod(array,axis=0) if compute_on_lines==False else np.prod(array,axis=1)

array=[[1,2,3,4],[1,-2,3,-4],[3,10,3,4]]
print(product(array,True))
print(product(array,False))

[ 24  24 360]
[  3 -40  27 -64]


In [45]:
# ex5
def matrix_compare(matrix_a: np.array, matrix_b: np.array) -> Tuple[int, int]:
    """Preia doua matrici pe care se verifica daca macar o valoare din prima
    este mai mare decat valoarea de pe acceasi pozitie din a doua 
    si returneaza un tuplu din indecsii respectivi daca exista iar daca nu 
    se returneaza None
    :param matrix_a,matrix_b: matrici de forma (m,n)
    :return: tuplu de indecsi sau None
    """
    result = np.where(matrix_a == matrix_b)
    try:
        return (result[0][0],result[1][0])
    except:
        return None
    
a = np.array([[1, 2, 3], [4, 5, 6], [7, 6, 3], [9, 9, 9]])
b = np.array([[5, 6, 5], [2, 5, 12], [-3, 6, 9], [0, -4, 2]])
print(matrix_compare(a, b))

(1, 1)


In [48]:
# ex6
def matrix_out_interval(matrix: np.array, interval: Tuple[int, int]) -> np.array:
    """Preia o matrice si un interval, returnand un vector cu pozitiile pe care 
    se afla valorile in afara intervalului.
    :param matrix: matrice
    :param interval: tuplu de int
    :return: vector cu pozitiile respective
    """
    line, column = np.where((matrix < interval[0]) | (matrix > interval[1]))
    return list(zip(line, column))

matrix = np.array([[11, 12, 13],
                    [14, 15, 16],
                    [17, 15, 11],
                    [12, 14, 15]])
matrix_out_interval(matrix, (12, 14))

[(0, 0), (1, 1), (1, 2), (2, 0), (2, 1), (2, 2), (3, 2)]

In [59]:
# ex7
def recursive_func(array: np.array) -> np.array:
    """Preia un vector pe care folosind indexarea logica, se inmultesc
    elementele din vector care sunt mai mici ca 100 cu 2 (restul raman neschimbate).
    Aplicand ciclarea pana cand toate elementele sunt >100, returneaza vectorul cu 
    numerele rezultate.
    :param array: vector de numere
    :return: vector cu numerele rezultate dupa ciclarea functiei
    """
    position = np.where(array < 100)[0]
    if len(position) == 0:
        return array
    else:
        array[np.array(position)] *= 2
        return recursive_func(array)

a = np.array([230, 10, 284, 39, 76])
print(recursive_func(a))

[230 160 284 156 152]


In [13]:
# ex8
def pair_max(array1: np.array,array2: np.array)->np.array:
    """Preia doi vectori de aceeasi lungime si returneaza un vector cu 
    maximele pe pozitiile corespunzatoare. Se verifica cu assert daca cei doi
    vectori au aceeasi lungime.
    :param array1,array2: vectori de aceeasi lungime
    :return: vector cu maximele de pe aceleasi pozitii
    """
    assert len(array1)==len(array2),"The lenght is not equal!"
    return np.maximum(array1,array2)

print(pair_max([3, 7, 9, 13, -10, 200,3],[4, 5, -9, 100, 300, 230, 1]))

[  4   7   9 100 300 230   3]


In [87]:
# ex9
data = np.genfromtxt('iris.data', delimiter = ',')
data = data[:, :-1]
nan_count = 0
while nan_count < 10:
    line = np.random.randint(np.ma.size(data, 0))
    column = np.random.randint(np.ma.size(data, 1))
    if np.isfinite(data[line, column]):
        data[line, column] = np.nan
        nan_count += 1
        """Se incarca datele din fisier intr-o matrice. Se cauta aleator 10
        pozitii in aceasta matrice de 150 linii si 4 coloane omitand ultima
        coloana, de tip text si se seteaza aceste valori pe NaN.
        """

def nan_counter(matrix: np.array) -> np.array:
    """Preia o matrice si returneaza un tuplu cu indicii de linii respectiv 
    de coloane in care se gasesc valori NaN.
    :param matrix: matrice de 150 linii si 4 coloane
    :return: vector de tuple
    """
    lines, columns = np.where(np.isnan(matrix))
    return list(zip(lines, columns))

print(nan_counter(data))


[(25, 0), (39, 0), (62, 1), (68, 0), (77, 3), (82, 2), (87, 2), (96, 1), (98, 3), (115, 1)]


In [52]:
# ex10
def min_k(array: np.array, k: int) -> np.array:
    """Preia un vector si un parametru implicit k. Returneaza cele mai mici 
    valori din acel vector de cel putin k elemente, impreuna cu pozitiile lor.
    :param array: vector de numere
    :param k: parametru implicit de tip int
    :return: vector de cel putin k elemente  
    """
    assert len(array) >= k, f"Given array is too short for k = {k}"
    return list(zip(np.sort(array)[:k], np.argsort(array)[:k]))
    
    
min_k(np.array([12, 12, 5, 6, -4, 2]), 3)

[(-4, 4), (2, 5), (5, 2)]

## Precizari
1. Se acorda 3 puncte din oficiu.
1. Tema se va prezenta in saptamana 16-20 martie 2020. 
1. Repository-ul va contine un fisier "readme.md" (in radacina repository-ului) in care vor fi mentionati autorii temelor, cu nume complet si grupa din care fac parte.